version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: sistema-educacional  
    ports:
      - "3306:3306"
    volumes:
      - my-vol:/var/lib/mysql
  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
volumes:
  my-vol: